### ISSUE TITLE
Problem with Aborted_clients 

### ISSUE THREAD

**Issue by teacplusplus** [brianmario/mysql2#794]
I have a problem with mysql2 gem 0.3.21 with ever-increasing Aborted_clients values. My rails version is 3.2.22.
sudo mysql -e "SHOW GLOBAL STATUS LIKE 'aborted_clients'";
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| Aborted_clients | 260   |
+-----------------+-------+

```
>> Mysql2::Client.new(host: "localhost", username: "root").close
>> Mysql2::Client.new(host: "localhost", username: "root").close
>> Mysql2::Client.new(host: "localhost", username: "root").close
```

sudo mysql -e "SHOW GLOBAL STATUS LIKE 'aborted_clients'";
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| Aborted_clients | 263   |
+-----------------+-------+
It brings a lot of problems such as big log file and sadness my boss. 
Our project has a lot of db requests. 
I can not use a different version of rails, since it is associated with long-term project migration.

**Comment by justincase** [comment]
This is fixed in #606. I don't think it was backported to `0.3.x` though.

**Comment by teacplusplus** [comment]
That would be great. There are many projects that run on older versions of ror. And I know it was broken in the 0.3.15 version.

**Comment by danielristic** [comment]
Me too with version `0.5.3` on rails `5.2`. This is not really a problem in itself as the log verbosity can be adjusted, but I noticed that consequently, the mysql connection does not get closed either when a unicorn process is killed due to a timeout, which under heavy load means that the maximum number of connections is not bounded and ends up reaching any given limit very quickly.

**Comment by ketandoshi** [comment]
@danielristic Did you found any solution for it? I'm using same versions - `0.5.3` on rails `5.2` - and still getting this error

**Comment by sodabrew** [comment]
`Aborted_clients` increments whenever a connection is torn down without the server having received `COM_QUIT`. Two independent ways to produce that:

1. A process opens a connection and is killed via SIGKILL or SIGSEGV or in some other way was unable to run a graceful shutdown and exit sequence,
2. A process opens a connection with `automatic_close: false` and exits normally, finalizers and all, without an explicit `client.close`

`automatic_close: false` exists to protect a connection that is shared across a `fork()`. Setting it commits the application to closing connections itself, from either the parent or child process, to ensure an orderly shutdown and avoid Aborted_clients counter increasing. See [Fork safety](https://github.com/brianmario/mysql2#fork-safety) for more information.
